### ISSUE TITLE
Add connect lost retry mechanism and raise event

### ISSUE THREAD

**Issue by lihongfang16** [dshe/RxSockets#1]

**Comment by dshe** [comment]
When the remote socket disconnects, it will notify the connected socket by sending 0 bytes. This will complete the RxClientSocket.ReceiveObservable. In case the connection gets severed without such notification, the observable will not complete. In both cases, RxClientSocket.Connected is false, and calling RxClientSocket.Send() more than once will throw a SocketException. Sensing and recovery from a severed connection may be practical at a higher level.
